framework:
    messenger:
        default_bus: command.bus
        transports:
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
        routing:
            Domain\ItemList\ListCreatedEvent: async
        buses:
            command.bus: ~
            event.bus:
                default_middleware: allow_no_handlers
