version: '3.5'
services:
    postgresql:
        image: postgres
        network_mode: host
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: algolia
        tmpfs:
            - /var/lib/postgresql/data
