imports:
    - { resource: item_list_services.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Algolia\AlgoliaSearch\SearchClient:
        factory: 'Algolia\AlgoliaSearch\SearchClient::create'
        arguments: ['%env(ALGOLIA_API_CLIENT)%', '%env(ALGOLIA_API_KEY)%']
