imports:
    - { resource: repositories.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Infra\:
        resource: '../src/Infra/*'
        exclude: '../src/Infra/{DependencyInjection,Migrations,Tests,Kernel.php}'

    Infra\Controller\:
        resource: '../src/Infra/Controller'
        tags: ['controller.service_arguments']

    Application\CreateList\CreateListService: ~
