name: deploy prod
on: [push]
env:
    DOCKER_BUILDKIT: 1
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build image
                run: docker image build --target=build_php --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg DUMP_ENV=0 --file=docker/Dockerfile --cache-from=ioni-todo/php:latest  --tag=ioni-todo/php:latest .
            -   name: Tag image
                run: docker image tag ioni-todo/php:latest ioni-todo/php:$GITHUB_RUN_ID
            -   name: Docker login
                uses: docker/login-action@v1
                with:
                    # registry: myregistry
                    username: ${{ DOCKER_USERNAME }}
                    password: ${{ DOCKER_PASSWORD }}
            -   name: Push images
                run: docker push ioni-todo/php:latest ioni-todo/php:$GITHUB_RUN_ID
