name: deploy prod
on: [push]
env:
    DOCKER_BUILDKIT: 1
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build and Push image PHP test
                uses: docker/build-push-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    repository: ioni/todo-php:test-latest
                    dockerfile: docker/Dockerfile
                    target: build_php_dev
                    build_args: BUILDKIT_INLINE_CACHE=1,DUMP_ENV=1,ENV=test
                    cache_froms: ioni/todo-php:test-latest
                    tags: test-latest
            -   name: Launch tests
                run: docker run --rm ioni/todo-php:test-latest bin/phpunit
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build and Push image PHP prod
                uses: docker/build-push-action@v1 # https://github.com/marketplace/actions/build-and-push-docker-images
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    repository: ioni/todo-php
                    dockerfile: docker/Dockerfile
                    target: build_php
                    build_args: BUILDKIT_INLINE_CACHE=1,DUMP_ENV=0
                    cache_froms: ioni/todo-php:latest
                    tags: latest
                    tag_with_ref: true
