name: deploy prod
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build and Push image PHP
                uses: docker/build-push-action@v1
                env:
                    DOCKER_BUILDKIT: 1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    repository: ioni-todo-php
                    dockerfile: docker/Dockerfile
                    target: build_php
                    build_args: BUILDKIT_INLINE_CACHE=1,DUMP_ENV=0
                    cache_froms: ioni-todo-php:latest
                    tags: latest
                    tag_with_ref: true
