name: deploy prod
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: DOCKER_BUILDKIT=1 docker image build --target=build_php --build-arg DUMP_ENV=0 --file=docker/Dockerfile --tag=ioni-todo/php:$(date +%s) .
